name: messio
description: Messio is a modern messaging app
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.8
  rubber: ^0.3.2
  cupertino_icons: ^0.1.2
  infinite_listview: ^1.0.0
  flutter_bloc: ^0.21.0 #helps in implementing blocs
  equatable: ^0.5.0 #helps in comparing class using their values
  image_picker: ^0.6.1+4 #image picker used for picking images from gallery
  flutter_launcher_icons: ^0.7.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ic_launcher.png"
  image_path_andrpoid: "assets/launcher/ic_launcher.png"
  adaptive_icon_background: "assets/launcher/ic_background.png"
  adaptive_icon_foreground: "assets/launcher/ic_foreground.png"


flutter:
  assets:
    - assets/
    - assets/launcher/
  uses-material-design: true
